// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Movie struct {
	ID          int32     `json:"id"`
	Name        string    `json:"name"`
	Summary     string    `json:"summary"`
	Language    string    `json:"language"`
	Genre       string    `json:"genre"`
	ReleaseDate time.Time `json:"release_date"`
}

type Rating struct {
	ID      int32 `json:"id"`
	MovieID int32 `json:"movie_id"`
	UserID  int32 `json:"user_id"`
	Rating  int32 `json:"rating"`
}

type Userdatum struct {
	ID           int32  `json:"id"`
	Name         string `json:"name"`
	Email        string `json:"email"`
	Role         string `json:"role"`
	Passwordhash string `json:"passwordhash"`
}
