// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Userdatum, error)
	EditMovie(ctx context.Context, arg EditMovieParams) ([]Movie, error)
	GetMovieByID(ctx context.Context, id int32) (Movie, error)
	GetMovieByName(ctx context.Context, name string) (Movie, error)
	GetMovieListBasedOnRating(ctx context.Context, rating int32) ([]Rating, error)
	GetMoviesByGenre(ctx context.Context, genre string) ([]Movie, error)
	GetMoviesByLanguage(ctx context.Context, language string) ([]Movie, error)
	GetRatingsGivenByUser(ctx context.Context, userID int32) ([]Rating, error)
	GetRatingsGivenToMovie(ctx context.Context, movieID int32) ([]Rating, error)
	GetUserByEmail(ctx context.Context, email string) (Userdatum, error)
	GetUserByName(ctx context.Context, name string) (Userdatum, error)
	GiveRating(ctx context.Context, arg GiveRatingParams) (Rating, error)
	ResetPassword(ctx context.Context, arg ResetPasswordParams) (ResetPasswordRow, error)
}

var _ Querier = (*Queries)(nil)
